version: '3.7'
services:
  ego-ui:
    image: overture/ego-ui:edge
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      REACT_APP_API: http://localhost:8081
      REACT_APP_EGO_CLIENT_ID: ego-ui
  api:
    # change the image tag to the target image as needed
    image: overture/ego:5.2.0
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ego?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: "classpath:flyway/sql,classpath:db/migration"
      SPRING_PROFILES_ACTIVE: auth
      google.client.clientId: $EGO_GOOGLE_CLIENT_ID
      google.client.clientSecret: $EGO_GOOGLE_SECRET
      default.user.firstUserAsAdmin: "true"
      logging.level.root: INFO
    expose:
      - "8081"
    ports:
      - "8081:8081"
    depends_on:
      - postgres
  postgres:
    image: postgres:12.6
    environment:
      - POSTGRES_DB=ego
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - "ego_data:/var/lib/postgresql/data"
volumes:
  ego_data: