FROM openjdk

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y maven && \
    mkdir -p /usr/src/app

WORKDIR /usr/src/app

# copy just the pom.xml and install dependencies for caching
ADD pom.xml .
RUN mvn verify clean --fail-never

ADD . .

EXPOSE 8081

RUN mvn install -DskipTests

CMD java -jar target/ego-*-SNAPSHOT-exec.jar \
    --spring.datasource.url="jdbc:postgresql://$EGO_DB_HOST:$EGO_DB_PORT/$EGO_DB?stringtype=unspecified" \
    --spring.datasource.username="$EGO_DB_USER" \
    --spring.datasource.password="$EGO_DB_PASS" \
    --google.client.ids="$EGO_SERVER_GOOGLE_CLIENT_IDS"