FROM maven:3.6-jdk-8

WORKDIR /usr/src/app

ADD . .

RUN mvn package -Dmaven.test.skip=true

FROM java:8-alpine

COPY --from=0 /usr/src/app/target/ego-*-SNAPSHOT-exec.jar /usr/bin/ego.jar
COPY --from=0 /usr/src/app/src/main/resources/flyway/sql /usr/src/flyway-migration-sql

ENTRYPOINT ["java", "-jar", "/usr/bin/ego.jar"]

EXPOSE 8081/tcp
