DROP TABLE IF EXISTS EGOAPPLICATION CASCADE;
DROP TABLE IF EXISTS EGOUSER CASCADE;
DROP TABLE IF EXISTS EGOGROUP CASCADE;
DROP TABLE IF EXISTS GROUPAPPLICATION CASCADE;
DROP TABLE IF EXISTS USERGROUP CASCADE;
DROP TABLE IF EXISTS USERAPPLICATION CASCADE;
