/*
 * Copyright (c) 2017. The Ontario Institute for Cancer Research. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.overture.ego.repository;

import org.overture.ego.model.QueryInfo;
import org.overture.ego.model.entity.Application;
import org.overture.ego.repository.mapper.ApplicationMapper;
import org.overture.ego.repository.sql.ApplicationQueries;
import org.skife.jdbi.v2.sqlobject.Bind;
import org.skife.jdbi.v2.sqlobject.BindBean;
import org.skife.jdbi.v2.sqlobject.SqlQuery;
import org.skife.jdbi.v2.sqlobject.SqlUpdate;
import org.skife.jdbi.v2.sqlobject.customizers.RegisterMapper;

import java.util.List;

@RegisterMapper(ApplicationMapper.class)
public interface ApplicationRepository {


  /*
    ID is autogenerated
   */
  @SqlUpdate(ApplicationQueries.INSERT_QUERY)
  int create(@BindBean Application application);

  @SqlQuery(ApplicationQueries.GET_BY_NAME)
  Application getByName(@Bind("name") String applicationName);

  @SqlQuery(ApplicationQueries.GET_BY_ID)
  Application read(@Bind("id") int id);

  //TODO: change updates to a function in DB that updates relationship tables too
  @SqlUpdate(ApplicationQueries.UPDATE_QUERY)
  int update(@Bind("id") int id, @BindBean Application application);

  @SqlUpdate(ApplicationQueries.DELETE_QUERY)
  int delete(@Bind("id") int id);

  @SqlQuery(ApplicationQueries.GET_ALL)
  List<Application> listApps(@BindBean QueryInfo queryInfo);
}
