CREATE TABLE APPLICATIONPERMISSION (
   id  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
   policy_id UUID,
   application_id UUID,
   access_level ACLMASK NOT NULL,
   FOREIGN KEY (policy_id) REFERENCES POLICY(id),
   FOREIGN KEY (application_id) REFERENCES EGOAPPLICATION(id)
);

ALTER TABLE APPLICATIONPERMISSION RENAME CONSTRAINT APPLICATIONPERMISSION_POLICY_ID_FKEY TO APPLICATIONPERMISSION_POLICY_FKEY;
ALTER TABLE APPLICATIONPERMISSION RENAME CONSTRAINT APPLICATIONPERMISSION_APPLICATION_ID_FKEY TO APPLICATIONPERMISSION_APPLICATION_FKEY;

CREATE INDEX idx_applicationpermission_application ON APPLICATIONPERMISSION(application_id);
CREATE INDEX idx_applicationpermission_policy ON APPLICATIONPERMISSION(policy_id);
CREATE INDEX idx_applicationpermission_both ON APPLICATIONPERMISSION(application_id, policy_id);
