ALTER TABLE USERGROUP ADD PRIMARY KEY (group_id,user_id);
ALTER TABLE USERAPPLICATION ADD PRIMARY KEY (user_id, application_id);
ALTER TABLE GROUPAPPLICATION ADD PRIMARY KEY (group_id, application_id);
