CREATE TABLE REFRESHTOKEN (
    id UUID PRIMARY KEY,
    user_id  UUID UNIQUE NOT NULL,
    jti UUID UNIQUE NOT NULL,
    issuedate TIMESTAMP NOT NULL DEFAULT NOW(),
    expirydate TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES EGOUSER(id)
);