ALTER TABLE EGOAPPLICATION
  MODIFY COLUMN id UUID;

ALTER TABLE EGOGROUP
  MODIFY COLUMN id UUID;

ALTER TABLE GROUPAPPLICATION
  MODIFY COLUMN grpId UUID;

ALTER TABLE GROUPAPPLICATION
  MODIFY COLUMN appId UUID;

ALTER TABLE USERGROUP
  MODIFY COLUMN grpId UUID;

ALTER TABLE USERAPPLICATION
  MODIFY COLUMN appId UUID;

