CREATE TABLE REFRESHTOKEN (
    user_id  UUID PRIMARY KEY,
    refresh_id UUID UNIQUE DEFAULT uuid_generate_v4(),
    jti UUID UNIQUE NOT NULL,
    issuedate TIMESTAMP NOT NULL DEFAULT NOW(),
    expirydate TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES EGOUSER(id)
);