CREATE TABLE TOKEN(
  id        UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  token     VARCHAR(2048) NOT NULL,
  owner     UUID NOT NULL REFERENCES EGOUSER(ID),
  issuedate TIMESTAMP DEFAULT NOW(),
  isrevoked BOOLEAN DEFAULT FALSE
);

CREATE TABLE TOKENSCOPE (
  tokenid   UUID NOT NULL REFERENCES TOKEN(ID),
  scopeid   UUID NOT NULL REFERENCES ACLENTITY(ID)
);

CREATE TABLE TOKENAPPLICATION (
  tokenid   UUID NOT NULL REFERENCES TOKEN(ID),
  appid     UUID NOT NULL REFERENCES EGOAPPLICATION(ID)
);
