ALTER TABLE EGOAPPLICATION ALTER COLUMN name SET NOT NULL;
ALTER TABLE EGOAPPLICATION ALTER COLUMN clientid SET NOT NULL;
ALTER TABLE EGOAPPLICATION ALTER COLUMN clientsecret SET NOT NULL;
ALTER TABLE EGOAPPLICATION ALTER COLUMN status SET NOT NULL;

ALTER TABLE EGOGROUP ALTER COLUMN name SET NOT NULL;
ALTER TABLE EGOGROUP ALTER COLUMN status SET NOT NULL;

ALTER TABLE EGOUSER ALTER COLUMN name SET NOT NULL;
ALTER TABLE EGOUSER ALTER COLUMN email SET NOT NULL;
ALTER TABLE EGOUSER ALTER COLUMN role SET NOT NULL;
ALTER TABLE EGOUSER ALTER COLUMN createdat SET NOT NULL;
-- ALTER TABLE EGOUSER ALTER COLUMN lastlogin SET NOT NULL;
ALTER TABLE EGOUSER ALTER COLUMN status SET NOT NULL;
-- ALTER TABLE EGOUSER ALTER COLUMN preferredlanguage SET NOT NULL;

ALTER TABLE GROUPAPPLICATION ALTER COLUMN group_id SET NOT NULL;
ALTER TABLE GROUPAPPLICATION ALTER COLUMN application_id SET NOT NULL;

ALTER TABLE GROUPPERMISSION ALTER COLUMN policy_id SET NOT NULL;
ALTER TABLE GROUPPERMISSION ALTER COLUMN group_id SET NOT NULL;

ALTER TABLE POLICY ALTER COLUMN owner SET NOT NULL;

ALTER TABLE TOKEN ALTER COLUMN issuedate SET NOT NULL;
ALTER TABLE TOKEN ALTER COLUMN isrevoked SET NOT NULL;

ALTER TABLE USERAPPLICATION ALTER COLUMN application_id SET NOT NULL;

ALTER TABLE USERGROUP ALTER COLUMN group_id SET NOT NULL;

ALTER TABLE USERPERMISSION ALTER COLUMN policy_id SET NOT NULL;
ALTER TABLE USERPERMISSION ALTER COLUMN user_id SET NOT NULL;
