CREATE TYPE APPLICATIONTYPE AS ENUM('CLIENT','ADMIN');
ALTER TABLE EGOUSER RENAME COLUMN role to usertype;
ALTER TABLE EGOAPPLICATION add column applicationtype APPLICATIONTYPE not null DEFAULT 'CLIENT';
