insert into egouser (id, name, email) values (uuid_generate_v4(), 'tester@test.org', 'tester.test.org');
insert into egogroup (name, description, status) values ('testers', 'People who test', 'Approved');
insert into egoapplication (name, clientid, clientsecret, status) values ('song','song','lalala', 'Approved');
insert into usergroup (userid, grpid) select U.id, G.id from egouser U, egogroup G;
insert into userapplication (userid, appid) select U.id, A.id from egouser U, egoapplication A;
insert into aclentity (id, owner, name) select uuid_generate_v4(), G.id, 'id.create' from egogroup G;
insert into aclentity (id, owner, name) select uuid_generate_v4(), G.id, 'song.upload' from egogroup G;
insert into aclentity (id, owner, name) select uuid_generate_v4(), G.id, 'song.download' from egogroup G;
insert into acluserpermission (id, entity, sid, mask) select uuid_generate_v4(),A.id, U.id, 'WRITE' from aclentity A, egouser U;
insert into token (token, owner) select '8e63cd16-2db8-448e-b48c-f3d9d3c2dc8e', U.id from egouser U;
insert into tokenscope (token_id, policy_id, access_level) select T.id, A.id, 'WRITE' from token T, aclentity A;
