#!/bin/bash
client_id="song"
client_secret="lalala"

# If you change the value of the token below, remember to change the 
# corresponding value in check_token_test.sql, or the test will fail.
token="8e63cd16-2db8-448e-b48c-f3d9d3c2dc8e"

./setup_database
./check_token ${token} ${client_id} ${client_secret}
